# Generated by Django 2.0.6 on 2018-07-12 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_auto_20180106_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateTimeField()),
                ('FatherName', models.CharField(blank=True, max_length=100)),
                ('MotherName', models.CharField(blank=True, max_length=100)),
                ('AddressLine1', models.CharField(blank=True, max_length=255)),
                ('AddressLine2', models.CharField(blank=True, max_length=255)),
                ('City', models.CharField(choices=[('Guwahati', 'Guwahati'), ('Chennai', 'Chennai')], default='Chennai', max_length=50)),
                ('State', models.CharField(choices=[('Assam', 'Assam'), ('Tamil Nadu', 'Tamil Nadu')], default='Tamil Nadu', max_length=50)),
                ('PinCode', models.CharField(blank=True, max_length=6)),
                ('PF', models.CharField(blank=True, max_length=20)),
                ('ESI', models.CharField(blank=True, max_length=20)),
                ('PAN', models.CharField(blank=True, max_length=10)),
                ('Aadhar', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Associates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
