# Generated by Django 2.2.10 on 2020-07-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='Hours',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
