# Generated by Django 2.0.6 on 2018-07-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_client_dependant_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associate',
            old_name='AddressLine1',
            new_name='Address_Line_1',
        ),
        migrations.RenameField(
            model_name='associate',
            old_name='AddressLine2',
            new_name='Address_Line_2',
        ),
        migrations.RenameField(
            model_name='associate',
            old_name='DateOfBirth',
            new_name='Date_of_Birth',
        ),
        migrations.RenameField(
            model_name='associate',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='associate',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='associate',
            old_name='PinCode',
            new_name='Pin_Code',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='AddressLine1',
            new_name='Address_Line_1',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='AddressLine2',
            new_name='Address_Line_2',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='PinCode',
            new_name='Pin_Code',
        ),
        migrations.RenameField(
            model_name='dependant',
            old_name='DateOfBirth',
            new_name='Date_of_Birth',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='QuoteDate',
            new_name='Quote_Date',
        ),
    ]
