# Generated by Django 2.2.10 on 2020-07-07 11:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200707_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Content',
            field=tinymce.models.HTMLField(default='test', verbose_name='Content'),
        ),
    ]
