# Generated by Django 2.0.6 on 2018-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20180713_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='FatherName',
            field=models.CharField(blank=True, max_length=100, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='associate',
            name='MotherName',
            field=models.CharField(blank=True, max_length=100, verbose_name="Mother's Name"),
        ),
    ]
