# Generated by Django 2.0.6 on 2018-08-17 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20180713_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependant',
            name='Date_of_Birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='Relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister')], default='Father', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='Quote_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
