# Generated by Django 2.0.6 on 2018-08-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20180817_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='Date_of_Birth',
            field=models.DateField(),
        ),
    ]
